In [20]:
import pandas as pd
import numpy as np
import os

In [11]:
def text_to_sentences(file_path):

	text_content = open(file_path , "r")

	text_string = text_content.read().replace("\n", " ")

	text_content.close()

	characters_to_remove = [";","'s", "@", "&","*", 
    "(",")","!","+","_",":", '"',"'"]

	for item in characters_to_remove:
		text_string = text_string.replace(item,"")
	characters_to_replace = ["?"]

	for item in characters_to_replace:
		text_string = text_string.replace(item,".")
	sentences = text_string.split(".")

	j = 0

	for sentence in sentences:
		if len(sentence.lstrip()) <= 1:
			continue
		elif sentence[0] == " ":
			sentence = sentence[1:]
			sentences[j] = sentence.lower() + '.'
			j += 1
		else:
			sentences[j] = sentence.lower() + '.'
			j += 1
	sentences = sentences[0:j]

	return(sentences)

In [12]:
file_path = '/content/drive/MyDrive/Omdena/fb62e200-0fa3-11ec-82a8-0242ac130003 (2).txt'

In [17]:
texts  = text_to_sentences(file_path)

In [18]:
import pandas as pd

df = pd.DataFrame(texts,columns=['text'])
df.head(20)

                                                 text
0   ﻿letter from the chairman   josé manuel entrec...
1     putting the growth of nations back on track ...
2     during these months in which our attention h...
3     we begin this new decade hopeful that we wil...
4     the solidarity we have seen in the streets a...
5     now is the time for accountability   in this...
6     during this period, acciona has managed to a...
7   this figure supposes more than 80 times the em...
8     in 2020, more than eight out of every ten eu...
9     to reach this point, however, we have taken ...
10  technologies integrated in acciona projects th...
11    sustainability has made us better   as we re...
12    our main competitive advantage comes from ou...
13                   from each and every one of them.
14  making them central to our decisions has been ...
15    in this financial year some of the measures ...
16    sor pant an = 11   report 2020       — index...
17  acciona has been designated a sustainability l...
18  however, in this financial year and in this re...
19  this human group has been exemplary in the way...

In [19]:
df.to_csv('accoin_result_phase2.csv', index=False)